# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: docker-image:tag

pipelines:
  default:
    - step:
        script:
          - cd ..
          - hg clone https://bitbucket.org/dimo414/profilegem
          - mv $BITBUCKET_CLONE_DIR profilegem/util.gem
          - cd profilegem
          - echo "#GEM util" > local.conf.sh
          - ./load.sh