name: CI

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    container: dimo414/ci-profilegem
    strategy:
      matrix:
        bash-version: [bash-5, bash-4, bash-3]

    steps:
    - uses: actions/checkout@v2
    - name: "Unit Tests - ${{ matrix.bash-version }}"
      run: ${{ matrix.bash-version }} -c 'bats test'
    - name: "Gem Tests - ${{ matrix.bash-version }}"
      run: ${{ matrix.bash-version }} /pgem_test/gem_test.sh .

  ShellCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: ShellCheck
        uses: docker://koalaman/shellcheck-alpine
        with:
          entrypoint: sh
          args: -c "find . -name '*.sh' -exec shellcheck --shell=bash --exclude=2034 {} +"